#!/bin/bash

echo "🛡️  Phishing Detection AI - Database Setup"
echo "========================================"
echo ""

echo "📋 You need to set up TWO databases:"
echo "1. MongoDB Atlas (for backend data storage)"
echo "2. Firebase (for user authentication)"
echo ""

echo "🔧 MONGODB SETUP (Backend):"
echo "=========================="
echo "1. Go to: https://www.mongodb.com/cloud/atlas"
echo "2. Create free account"
echo "3. Create new cluster (free tier)"
echo "4. Get connection string"
echo "5. Create .env file in backend folder:"
echo ""
echo "   MONGODB_URL=mongodb+srv://username:password@cluster0.xxxxx.mongodb.net/phishing_detection?retryWrites=true&w=majority"
echo ""

echo "🔥 FIREBASE SETUP (Frontend):"
echo "============================"
echo "1. Go to: https://console.firebase.google.com/"
echo "2. Create project: phishing-detection-ai"
echo "3. Enable Email/Password authentication"
echo "4. Create Firestore database (test mode)"
echo "5. Get Firebase config"
echo "6. Update frontend/firebase-config.js"
echo ""

echo "📁 FILES TO CREATE/EDIT:"
echo "======================="
echo "1. backend/.env (create this file)"
echo "2. frontend/firebase-config.js (edit existing)"
echo ""

echo "🚀 AFTER SETUP:"
echo "==============="
echo "1. Restart backend: cd backend && python -m uvicorn app.main:app --reload --port 3000"
echo "2. Refresh frontend: http://localhost:8081/phishing-detection-ai-starter/frontend/index.html"
echo "3. Test sign up with a new account"
echo ""

echo "📚 Detailed instructions: DATABASE_SETUP.md"
echo ""
echo "✅ Once both are configured, your app will have:"
echo "   • User authentication (Firebase)"
echo "   • Data storage (MongoDB)"
echo "   • Email analysis (Backend API)"
echo "   • Beautiful landing page (Frontend)"
echo ""
